#!/bin/bash

set -e
if [[ -z $1 ]]; then
    echo "Usage: $0 <Makefile out dir>"
    exit 1
fi

OLD_SRC="src/plugin/plugin_event.c"
MK_FILE=$(echo $OLD_SRC | sed 's|src/|'"$1/"'|;s|\.c|\.mk|')
NEW_SRC=$(pre_proc.sh $OLD_SRC 39 "" "^#define PL" "^#undef PL")

cat << EOF > $MK_FILE
# Auto-generated from $OLD_SRC. Do not edit! Generated by $0 $1 $(date)
REMOVAL += $OLD_SRC
ADDITION += $NEW_SRC
EOF
