#!/bin/bash

set -e
if [[ -z $1 ]]; then
    echo "Usage: $0 <Makefile out dir>"
    exit 1
fi

MK_FILE=${1%.sh}
OLD_SRC="src/plugin/plugin_event.c"
NEW_SRC=$(pre_proc.sh $OLD_SRC 31 "" "^#define PL" "^#undef PL")

echo <<EOF
# Auto-generated from $OLD_SRC. Do not edit!
# Generated by $0 $1 $(date)
CSRC := \$(filter-out %.sh,\$(CSRC)) $NEW_SRC
EOF
> $MK_FILE
echo $MK_FILE
