name: Build simpleHttpd

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install clang, libmagic
      run : apt update -y && apt install -y clang libmagic-dev build-essential  
    - name: Install lua
      run: wget https://www.lua.org/ftp/lua-5.4.6.tar.gz && tar xf lua-5.4.6.tar.gz && ln -s `pwd`/lua-5.4.6/ `pwd`/lua && make -C lua all install 
    - name: make
      run: make
    - name: setup go
      uses: https://github.com/actions/setup-go@v4
      with:
        go-version: '>=1.20.1'
    - name: Release dev build
      uses: https://gitea.com/actions/release-action@main
      with:
        files: |-
          simpleHttpd            
        api_key: '${{secrets.RELEASE_TOKEN}}'
