name: Build simpleHttpd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: get lua
      run: wget https://www.lua.org/ftp/lua-5.4.6.tar.gz
    - name: untar lua
      run: tar xvf lua-5.4.6.tar.gz
    - name: link lua src to lua 
      run: ln -s `pwd`/lua-5.4.6/src/ `pwd`/lua
    - name: Compile lua
      run: cd lua && make && make install
    - name: ls
      run: ls
    - name: make
      run: make
