name: Build simpleHttpd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install clang, libmagic
      run : apt update -y && apt install -y clang libmagic-dev build-essential
    - name: Install lua
      run: wget https://www.lua.org/ftp/lua-5.4.6.tar.gz && tar xf lua-5.4.6.tar.gz && ln -s `pwd`/lua-5.4.6/ `pwd`/lua && make -j -C lua all install 
    - name: make
      run: make -j
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITEA_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "SimpleHttpd auto shit!"
        files: |
          simpleHttpd
